# Generated by Django 4.0.4 on 2022-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
